# Specify video quality [default: 720] [possible values: 360, 480, 720]
quality=720

# Netscape formatted file to read cookies from (need for media database integration)
cookies=~/cookies.txt

# Specify translation title
translation_title=Subtitles

# Specify translation type [possible values: voice, subtitles] (fallback if translation_title not found)
translation_type=voice

# Expand a media database URL into all related URLs [possible values: all, essential]
related_mode=essential
